### ISSUE TITLE
Support for MSSQL Geometry & Geography types?

### ISSUE THREAD

**Issue by legomind** [fsprojects/SQLProvider#157] opened 2015-09-15 18:08 UTC
Title says it all.

When querying a table with either of those types, all the other columns are visible but the spatial types.

``` sql
ALTER TABLE test.Addresses
ADD Coordinates GEOMETRY
```

**Comment by colinbull** [comment] 2015-09-15 18:21
This is currently by design.. Due to problems resolving those types at design time and runtime. There are techniques to get around this that are used heavily in other type providers. We will implement this in the future but the current focus is to get a solid v1 release out of the door. 

It is worth noting that the same is true for the more advanced types in all of the other providers.

**Comment by pezipink** [comment] 2015-09-15 19:36
Yes this one is tricky to do nicely..  it is certainly on the list of potential development though.

**Comment by reinux** [comment] 2020-05-01 02:56
Has the situation on this changed at all? Or are there any workarounds?

**Comment by Thorium** [comment] 2020-05-01 11:18
Some initial work in 1.1.85, let me know how is it working for you.

**Comment by reinux** [comment] 2020-05-01 17:59
That's awesome. Thanks!

Just played with it for a couple minutes and saw that IntelliSense picks it up. Will play with it more tonight.

**Comment by reinux** [comment] 2020-05-02 21:27
Hmm, running into this exception:

```
System.ArgumentException: UdtTypeName property must be set for UDT parameters.
   at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters, Boolean includeReturnValue)
   at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at <StartupCode$FSharp-Data-SqlProvider>.$Providers.MsSqlServer.FSharp-Data-Sql-Common-ISqlProvider-ProcessUpdates@1058.Invoke(SqlEntity e)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
   at FSharp.Data.Sql.Providers.MSSqlServerProvider.FSharp-Data-Sql-Common-ISqlProvider-ProcessUpdates(IDbConnection con, ConcurrentDictionary`2 entities, TransactionOptions transactionOptions, FSharpOption`1 timeout)
   at <StartupCode$FSharp-Data-SqlProvider>.$SqlRuntime.DataContext.action@1-11(SqlDataContext __, IDbConnection con, Unit unitVar0)
   at FSharp.Data.Sql.Runtime.SqlDataContext.FSharp-Data-Sql-Common-ISqlDataContext-SubmitPendingChanges()
   at <StartupCode$FSI_0013>.$FSI_0013.main@()
```

I don't think I have access to the `SqlParameter` that's being generated, so I think this may have to be specified by SQLProvider. Might I be missing something?

**Comment by Thorium** [comment] 2020-05-04 13:14
In my queries I didn't have the corresponding assembly (Microsoft.SqlServer.Types.dll) so I just did .ToString() and got the select- and where-clauses working.

How can I reproduce this issue, can you give me code sample what would generate the exception (e.g. is it select/where/insert/update/...)?

Yes SQLProviders construcst SqlParameter-classes and they do have a property "UdtTypeName",
so we should be able to populate it in Providers.MsSqlServer.fs. I expect the correct values are just "Geometry"/"Geography"/"HierarchyId".

**Comment by reinux** [comment] 2020-05-04 17:36
I'm just updating a single row, like this:

```
let wgs84 = 4326    // https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84
let addr = dc.Dbo.Addresses.Individuals.``705712965776576512``
let pt = Microsoft.SqlServer.Types.SqlGeography.Point(30., 40., wgs84)
addr.Location <- pt
dc.SubmitUpdates()
```

I'm pretty sure I got it right, but I can't rule out the possibility that I'm not using the Point type correctly.

**Comment by Thorium** [comment] 2020-05-05 10:22
The SQLParameter UdtTypeName is fixed in the latest version.

**Comment by reinux** [comment] 2020-05-05 17:58
Thank you!

**Closed** 2020-05-06 07:17 UTC
Labels: enhancement
