### ISSUE TITLE
Crash in PostgresqlProvider

### ISSUE THREAD

**Issue by trondd** [fsprojects/SQLProvider#132] opened 2015-04-03 06:58 UTC
I am not sure where the exact problem is, but I've provided a testcase to reproduce is. I am using a database created from the supplied sql scripts.

    open System.Data
    open System.Linq
    open FSharp.Data.Sql

    type sql = SqlDataProvider< 
              @"Server=",
              Common.DatabaseProviderTypes.POSTGRESQL,
              "Npgsql.2.2.5/lib/net40",
              UseOptionTypes = true >

    let getData =
        let ctx = sql.GetDataContext()
        let q = query { for record in ctx.``[public].[regions]`` do
                    
                        // This is ok
                        //where (record.region_name =% "Europe")

                        // This is not ok
                        where (record.region_id = 1)

                        select record.region_name.Value
                        }
        // Crash on the following statement
        let l = Seq.toList q
        l

    [<EntryPoint>]
    let main argv = 
        let l = getData
        List.iter (fun e -> printfn "%s" e) l
        0

Stack trace:

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for Program ---> System.TypeInitializationException: An exception was thrown by the type initializer for <StartupCode$foobar>.$Program ---> System.Reflection.AmbiguousMatchException: Ambiguous matching in method resolution
  at System.Reflection.Binder+Default.GetBetterMethod (System.Reflection.MethodBase m1, System.Reflection.MethodBase m2, System.Type[] types) [0x00000] in <filename unknown>:0 
  at System.Reflection.Binder+Default.SelectMethod (BindingFlags bindingAttr, System.Reflection.MethodBase[] match, System.Type[] types, System.Reflection.ParameterModifier[] modifiers, Boolean allowByRefMatch, System.Object[]& arguments) [0x00000] in <filename unknown>:0 
  at System.Reflection.Binder+Default.BindToMethod (BindingFlags bindingAttr, System.Reflection.MethodBase[] match, System.Object[]& args, System.Reflection.ParameterModifier[] modifiers, System.Globalization.CultureInfo culture, System.String[] names, System.Object& state) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes) [0x00000] in <filename unknown>:0 
  at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <filename unknown>:0 
  at FSharp.Data.Sql.Providers.PostgresqlProvider.FSharp-Data-Sql-Common-ISqlProvider-CreateCommandParameter (System.String name, System.Object value, Microsoft.FSharp.Core.FSharpOption`1 dbType) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+createParam@308-2.Invoke (System.Object value) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+extractData@317-4T[System.Object].Invoke (Microsoft.FSharp.Core.FSharpOption`1 data) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+build@316-29[System.Object].Invoke (Int32 i, System.Tuple`4 tupledArg) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Primitives.Basics.List.loop@171-14[Tuple`4] (Microsoft.FSharp.Core.FSharpFunc`3 f, Int32 n, Microsoft.FSharp.Collections.FSharpList`1 x) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Primitives.Basics.List.iteri[Tuple`4] (Microsoft.FSharp.Core.FSharpFunc`2 action, Microsoft.FSharp.Collections.FSharpList`1 x) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.IterateIndexed[Tuple`4] (Microsoft.FSharp.Core.FSharpFunc`2 action, Microsoft.FSharp.Collections.FSharpList`1 list) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+build@314-28T[System.Object].Invoke (System.String op, Microsoft.FSharp.Collections.FSharpList`1 preds, Microsoft.FSharp.Core.FSharpOption`1 rest) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[System.String,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`4[System.String,System.String,FSharp.Data.Sql.ConditionOperator,Microsoft.FSharp.Core.FSharpOption`1[System.Object]]]].InvokeFast[FSharpOption`1,Unit] (Microsoft.FSharp.Core.FSharpFunc`2 func, System.String arg1, Microsoft.FSharp.Collections.FSharpList`1 arg2, Microsoft.FSharp.Core.FSharpOption`1 arg3) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+filterBuilder@311-2.Invoke (Microsoft.FSharp.Collections.FSharpList`1 _arg4) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+aux@346-3[System.Object].Invoke (Microsoft.FSharp.Collections.FSharpList`1 _arg5) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.OptionModule.Iterate[FSharpList`1] (Microsoft.FSharp.Core.FSharpFunc`2 action, Microsoft.FSharp.Core.FSharpOption`1 option) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+build@314-28T[System.Object].Invoke (System.String op, Microsoft.FSharp.Collections.FSharpList`1 preds, Microsoft.FSharp.Core.FSharpOption`1 rest) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.FSharpFunc`2[System.String,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`4[System.String,System.String,FSharp.Data.Sql.ConditionOperator,Microsoft.FSharp.Core.FSharpOption`1[System.Object]]]].InvokeFast[FSharpOption`1,Unit] (Microsoft.FSharp.Core.FSharpFunc`2 func, System.String arg1, Microsoft.FSharp.Collections.FSharpList`1 arg2, Microsoft.FSharp.Core.FSharpOption`1 arg3) [0x00000] in <filename unknown>:0 
  at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+filterBuilder@311-2.Invoke (Microsoft.FSharp.Collections.FSharpList`1 _arg4) [0x00000] in <filename unknown>:0 
  at FSharp.Data.Sql.Providers.PostgresqlProvider.FSharp-Data-Sql-Common-ISqlProvider-GenerateQueryText (FSharp.Data.Sql.Common.SqlQuery sqlQuery, System.String baseAlias, FSharp.Data.Sql.Schema.Table baseTable, System.Collections.Generic.Dictionary`2 projectionColumns) [0x00000] in <filename unknown>:0 
  at FSharp.Data.Sql.QueryExpression.QueryExpressionTransformer.convertExpression (FSharp.Data.Sql.Common.SqlExp exp, System.Collections.Generic.List`1 entityIndex, IDbConnection con, ISqlProvider provider) [0x00000] in <filename unknown>:0 
  at FSharp.Data.Sql.Runtime.QueryImplementation.executeQuery (ISqlDataContext dc, ISqlProvider provider, FSharp.Data.Sql.Common.SqlExp sqlExp, System.Collections.Generic.List`1 ti) [0x00000] in <filename unknown>:0 
  at FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[System.String].System-Collections-Generic-IEnumerable`1-GetEnumerator () [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.SeqModule.ToList[String] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at <StartupCode$foobar>.$Program..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Program..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---

**Comment by pezipink** [comment] 2015-04-03 10:41
A crash!  Virtually unheard of!  We will look at this - thanks.  Looks a bit odd, it seems to have ended up in the stored procedure execution code when it should not be there.  This stuff changed around quite a bit since I originally wrote it - any immediate ideas @colinbull @janno-p  ?

**Comment by psfblair** [comment] 2015-07-14 04:00
I'm seeing the same thing with maybe a simpler case, also with PostgreSQL.

SQL:

    CREATE USER benchmarkdbuser WITH PASSWORD 'benchmarkdbpass';
    CREATE DATABASE hello_world WITH ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE hello_world to benchmarkdbuser;
    
    CREATE TABLE  World (
       id integer NOT NULL,
       randomNumber integer NOT NULL default 0,
       PRIMARY KEY  (id)
    );

Code: 

    open System
    open FSharp.Data.Sql
    open NUnit.Framework
    
    type sql = SqlDataProvider<DatabaseVendor    = Common.DatabaseProviderTypes.POSTGRESQL, 
                            ConnectionString = "Host=127.0.0.1;Port=5432;Database=hello_world;Username=benchmarkdbuser;Password=benchmarkdbpass;Pooling=true;MinPoolSize=5;MaxPoolSize=20",
                            UseOptionTypes = true>
    
    let singleRandomQueryFromWorld (random: Random) (dataContext: sql.dataContext) = 
        let key: int = random.Next(1, 10000)
        let record = query {
                    for row in dataContext.``[public].[World]`` do  
                    where (row.id = key)
                    select row
                 } |> Seq.head

    [<Test>]
    let ``should retrieve a record from a single random query`` () = 
        let record = singleRandomQueryFromWorld (System.Random()) (sql.GetDataContext())
        Assert.AreEqual(1, record.id)

Result:
    
      System.Reflection.AmbiguousMatchException : Ambiguous matching in method resolution
        at System.Reflection.Binder+Default.GetBetterMethod (System.Reflection.MethodBase m1, System.Reflection.MethodBase m2, System.Type[] types) [0x000f4] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System.Reflection/Binder.cs:802 
        at System.Reflection.Binder+Default.SelectMethod (BindingFlags bindingAttr, System.Reflection.MethodBase[] match, System.Type[] types, System.Reflection.ParameterModifier[] modifiers, Boolean allowByRefMatch, System.Object[]& arguments) [0x00264] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System.Reflection/Binder.cs:720 
        at System.Reflection.Binder+Default.BindToMethod (BindingFlags bindingAttr, System.Reflection.MethodBase[] match, System.Object[]& args, System.Reflection.ParameterModifier[] modifiers, System.Globalization.CultureInfo culture, System.String[] names, System.Object& state) [0x001af] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System.Reflection/Binder.cs:409 
        at System.Activator.CreateInstance (System.Type type, BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00043] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System/Activator.cs:250 
        at System.Activator.CreateInstance (System.Type type, System.Object[] args, System.Object[] activationAttributes) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System/Activator.cs:224 
        at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System/Activator.cs:219 
        at FSharp.Data.Sql.Providers.PostgresqlProvider.FSharp-Data-Sql-Common-ISqlProvider-CreateCommandParameter (System.String name, System.Object value, Microsoft.FSharp.Core.FSharpOption`1 dbType) [0x00000] in <filename unknown>:0 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+createParam@308-2.Invoke (System.Object value) [0x00000] in <filename unknown>:0 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+extractData@317-4T[System.Object].Invoke (Microsoft.FSharp.Core.FSharpOption`1 data) [0x00000] in <filename unknown>:0 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+build@316-29[System.Object].Invoke (Int32 i, System.Tuple`4 tupledArg) [0x00000] in <filename unknown>:0 
        at Microsoft.FSharp.Primitives.Basics.List.loop@171-14[Tuple`4] (Microsoft.FSharp.Core.FSharpFunc`3 f, Int32 n, Microsoft.FSharp.Collections.FSharpList`1 x) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-1f79c04/src/fsharp/FSharp.Core/local.fs:171 
        at Microsoft.FSharp.Primitives.Basics.List.iteri[Tuple`4] (Microsoft.FSharp.Core.FSharpFunc`2 action, Microsoft.FSharp.Collections.FSharpList`1 x) [0x00008] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-1f79c04/src/fsharp/FSharp.Core/local.fs:171 
        at Microsoft.FSharp.Collections.ListModule.IterateIndexed[Tuple`4] (Microsoft.FSharp.Core.FSharpFunc`2 action, Microsoft.FSharp.Collections.FSharpList`1 list) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-1f79c04/src/fsharp/FSharp.Core/list.fs:78 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+build@314-28T[System.Object].Invoke (System.String op, Microsoft.FSharp.Collections.FSharpList`1 preds, Microsoft.FSharp.Core.FSharpOption`1 rest) [0x00000] in <filename unknown>:0 
        at Microsoft.FSharp.Core.FSharpFunc`2[System.String,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`4[System.String,System.String,FSharp.Data.Sql.ConditionOperator,Microsoft.FSharp.Core.FSharpOption`1[System.Object]]]].InvokeFast[FSharpOption`1,Unit] (Microsoft.FSharp.Core.FSharpFunc`2 func, System.String arg1, Microsoft.FSharp.Collections.FSharpList`1 arg2, Microsoft.FSharp.Core.FSharpOption`1 arg3) [0x00000] in <filename unknown>:0 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+filterBuilder@311-2.Invoke (Microsoft.FSharp.Collections.FSharpList`1 _arg4) [0x00000] in <filename unknown>:0 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+aux@346-3[System.Object].Invoke (Microsoft.FSharp.Collections.FSharpList`1 _arg5) [0x00000] in <filename unknown>:0 
        at Microsoft.FSharp.Core.OptionModule.Iterate[FSharpList`1] (Microsoft.FSharp.Core.FSharpFunc`2 action, Microsoft.FSharp.Core.FSharpOption`1 option) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-1f79c04/src/fsharp/FSharp.Core/option.fs:39 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+build@314-28T[System.Object].Invoke (System.String op, Microsoft.FSharp.Collections.FSharpList`1 preds, Microsoft.FSharp.Core.FSharpOption`1 rest) [0x00000] in <filename unknown>:0 
        at Microsoft.FSharp.Core.FSharpFunc`2[System.String,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`4[System.String,System.String,FSharp.Data.Sql.ConditionOperator,Microsoft.FSharp.Core.FSharpOption`1[System.Object]]]].InvokeFast[FSharpOption`1,Unit] (Microsoft.FSharp.Core.FSharpFunc`2 func, System.String arg1, Microsoft.FSharp.Collections.FSharpList`1 arg2, Microsoft.FSharp.Core.FSharpOption`1 arg3) [0x00000] in <filename unknown>:0 
        at <StartupCode$FSharp-Data-SqlProvider>.$Providers.Postgresql+filterBuilder@311-2.Invoke (Microsoft.FSharp.Collections.FSharpList`1 _arg4) [0x00000] in <filename unknown>:0 
        at FSharp.Data.Sql.Providers.PostgresqlProvider.FSharp-Data-Sql-Common-ISqlProvider-GenerateQueryText (FSharp.Data.Sql.Common.SqlQuery sqlQuery, System.String baseAlias, FSharp.Data.Sql.Schema.Table baseTable, System.Collections.Generic.Dictionary`2 projectionColumns) [0x00000] in <filename unknown>:0 
        at FSharp.Data.Sql.QueryExpression.QueryExpressionTransformer.convertExpression (FSharp.Data.Sql.Common.SqlExp exp, System.Collections.Generic.List`1 entityIndex, IDbConnection con, ISqlProvider provider) [0x00000] in <filename unknown>:0 
        at FSharp.Data.Sql.Runtime.QueryImplementation.executeQuery (ISqlDataContext dc, ISqlProvider provider, FSharp.Data.Sql.Common.SqlExp sqlExp, System.Collections.Generic.List`1 ti) [0x00000] in <filename unknown>:0 
        at FSharp.Data.Sql.Runtime.QueryImplementation+SqlQueryable`1[FSharp.Data.Sql.Common.SqlEntity].System-Collections-Generic-IEnumerable`1-GetEnumerator () [0x00000] in <filename unknown>:0 
        at Microsoft.FSharp.Collections.SeqModule.Head[SqlEntity] (IEnumerable`1 source) [0x00000] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-1f79c04/src/fsharp/FSharp.Core/seq.fs:1547 
        at Benchmarks.WebSharper.SqlProvider.Data.singleRandomQueryFromWorld (System.Random random, System.Object dataContext) [0x0000e] in /Users/paulblair/Documents/workspaces-WebSharper/websharper-sqlprovider/Db.fs:14 
        at Benchmarks.WebSharper.SqlProvider.Tests.Data.should retrieve a record from a single random query () [0x00000] in /Users/paulblair/Documents/workspaces-WebSharper/websharper-sqlprovider/Tests/DbTest.fs:12 
        at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
        at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr2/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/mono-4.0.2/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

**Comment by janno-p** [comment] 2015-07-14 05:44
This should be fixed in master. Analyzing stack trace reveals that the problem occurs in 0.0.9 version here:

```F#
member __.CreateCommandParameter(name,value,dbType) = 
            let p = Activator.CreateInstance(paramterType,[|box name;box value|]) :?> IDbDataParameter
```

NpgsqlParameter has at least 3 overloads with 2 parameters, so they probably get mixed up somehow. In master the code uses default constructor to initialize parameter, so there shouldn't be any ambiguity possible.

I tried given sample with both versions: could reproduce in 0.0.9, but master worked as expected.

**Comment by psfblair** [comment] 2015-07-17 02:52
Thanks! Any idea when we might get a new version in NuGet (or an official release)? It looks like the version that's currently out there is from May 2014. It would be nice if the version available from NuGet didn't have this issue.

**Comment by pezipink** [comment] 2015-07-17 12:26
Yes, aiming for a v1.0 soon, sorry!

**Closed by pezipink** 2015-07-17 12:26 UTC
