### ISSUE TITLE
SqlDataProvider unable to accept non string arguments

### ISSUE THREAD

**Issue by jackmott** [fsprojects/SQLProvider#289] opened 2016-06-21 13:19 UTC
### Description

As soon as you provide one of the optional non string parametesr to the SqlDataProvider, you get an inscrutable error

### Repro steps
```fsharp
    let [<Literal>] connString = "Server=127.0.0.1;User Id=website; Password=alphapass;Database=alphamantis;"
    let [<Literal>] connexStringName = "DefaultConnectionString"
    let [<Literal>] dbVendor = Common.DatabaseProviderTypes.POSTGRESQL
    let [<Literal>] indivAmount = 100
    let [<Literal>] resPath = @"..\packages\Npgsql\lib\net451\"
    let [<Literal>] useOptTypes  = true

    type sql =
        SqlDataProvider<
            dbVendor,
            connString,
            connexStringName,
            resPath,
            indivAmount,
            useOptTypes
            >
```

### Expected behavior

The type provider should now be available

### Actual behavior

The following error is reported:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The type provider 'FSharp.Data.Sql.SqlTypeProvider' reported an error: Expected provided type named 'SqlDataProvider,DatabaseVendor="2",ConnectionString="Server=127.0.0.1;User Id=website; Password=alphapass;Database=alphamantis;",ConnectionStringName="DefaultConnectionString",ResolutionPath="..\\packages\\Npgsql\\lib\\net451\\",IndividualsAmount="100",UseOptionTypes="True"' but provided type has 'Name' with value 'SqlDataProvider,DatabaseVendor="2",ConnectionString="Server=127.0.0.1;User Id=website; Password=alphapass;Database=alphamantis;",ConnectionStringName="DefaultConnectionString",ResolutionPath="..\\packages\\Npgsql\\lib\\net451\",IndividualsAmount=\"100\",UseOptionTypes=\"True"'	AlphaFront	C:\projects\AlphaFront\AlphaFront\Db.fs	24	
```

### Known workarounds

I have tried various permutations, nothing works

### Related information 

* Windows 10
* Nuget version 1.0.17
* Visual Studio 2015 update 2 targeting .net 4.51

**Comment by Thorium** [comment] 2016-06-21 13:29
Try  `[<Literal>] let indivAmount = 100` instead of `let [<Literal>] indivAmount = 100`

**Comment by jackmott** [comment] 2016-06-21 13:38
I tried using named parameters, that also does not work, same error.
Moving the literal tag does not work.

**Comment by pezipink** [comment] 2016-06-21 15:03
try dropping the trailing \ from your resolution path?  There is a bug in the underlying type provider infrastructure that sometimes appears and causes these sorts of problems.

**Comment by jackmott** [comment] 2016-06-21 15:08
That did it.  I'm going to  update the docs, as they have that trailing slash, guiding users into this bug.

**Comment by pezipink** [comment] 2016-06-21 15:09
Ok, it is a funny once since it does not happen all the time. I am not sure if it is the provided types API or the TP infrastructure in the compiler itself - I will try and get some time to try and reproduce this in an easy way and report it.

**Comment by jackmott** [comment] 2016-06-21 15:21
I've done a PR for the docs removing trailing slashes in the examples. 
Maybe we should leave this open until we can report the bug to the F# team?

**Comment by Thorium** [comment] 2016-06-23 21:42
Report the bug or not, but we don't need open non-our-bugs hanging here so we can more easily focus the existing ones that matter. So I'll close this.

**Closed by Thorium** 2016-06-23 21:42 UTC
