### ISSUE TITLE
Caching of provided types

### ISSUE THREAD

**Issue by forki** [fsprojects/SQLProvider#178] opened 2015-11-30 16:01 UTC
I'm working with @tforkmann on a project and we try to use SQLProvider.
Unfortunately I don't have access to the db so the type provider can't generate types on my machine.
Is there a way for @tforkmann to commit "cached" types so that I can build on my machine and look at the code?

**Comment by colinbull** [comment] 2015-11-30 16:10
Not currently, there was talk of serializing the type signatures to a file location. I don't think any work started on it thou. But it is definitely something that is possible.

**Comment by pezipink** [comment] 2015-11-30 16:19
Possible yes, the core of it is pretty easy to implement but it has a larger impact across everything else and will have some dragons that need taming.

It is one of the 3 bigger ticket items that we would like to do should we ever get the time :)

**Comment by forki** [comment] 2015-11-30 16:21
@pezipink so this reads like you accept the challenge of dragon taming ;-)

jus kidding, it's not that important. I will find a way to #IF out.

**Comment by kerams** [comment] 2016-01-24 15:48
This would indeed be extremely useful. Currently, the type provider seems to hit the database on every single file save, completely killing intellisense until it succeeds or fails (which is not too uncommon for some reason).

**Comment by gibranrosa** [comment] 2017-05-18 04:32
I've started to work on it today, there is something already, and it was surprisingly easy until now. The branch name is "serialize" in my fork. If you guys could check it out, it would be great! :)

**Comment by Thorium** [comment] 2017-05-18 07:40
There are currently inmemory caches for generated tables and columns.
Some notes:

 - .NET thead-safety, e.g. Visual Studio creates a lot of threads. Thats' why current are ConcurrentDictionary GetOrAdd.
 - Cache invalidation? How much memory is ok to use for e.g. if SQLProvider is run on webserver? What if schema changes? 
 - What happens when user changes provider static parameters? Currently if it finds an error, it resets the generated types.
 - Connections: Current cloud architectures are pay-by-use so we would want to avoid unnecesary SQL-clauses. That's why there is a concurrent dictionary to hold connection cache in designtime.fs.
 - Offline-cache and multi-platform: Where to save data so that it would still work on both Windows and Mono

**Comment by pezipink** [comment] 2017-05-18 09:44
A few more things off the top of my head to think about with respect to offline-caching:

* A main selling point of the SQLProvider is that it accesses the schema lazily.  Thus, we'd only want to cache the types that are actually used.  

* Partially cached types would probably need to be extended during "online" development.  Do we also check for deltas, or simply have the user delete the cache in order to receive updated schema?

* How much control do we give to the user for caching? Should it be fully controlled by a static parameter, or automatically attempt to cache when "online", only using types when a connection can't be made? 

* Various threading and IDE issues

*Versioning?  Perhaps this isn't that important since the user can delete their cache, but we wouldn't want a new version of the SQLProvider to suddenly break their compile due to an old cache.

* It would be nice to avoid any library dependencies since we have managed this far no have none except the provided types api!

**Comment by gibranrosa** [comment] 2017-05-18 13:30
Yes, the real world, scary! :/ 
Some answers I would propose:
* It would be an extra feature, and it would have a parameter to activate it
* The concernment about multi-platform I would say in a first moment, one more parameter with the path
* I would say that this feature would be recomendable only for almost stable schemas. It would be only one more layer of caching. Or for sharing, as the original question of this issue.
* And lastly, if it is to avoid library dependencies, in that case... I will keep this to myself, because serializing by hand, this I pass :p 

The problem really IMHO is the threading, that already got me yesterday, and I will try to deal with it today.
But in summary I propose this to be, at the first moment at least, an extra feature for those who would deal with a very big and stable schema, for whom the constant update of a schema that does not change is in itself a problem.
And of course, that will be an initial version, that could be enhanced with the time.
What do you think?

Anywho, thanks guys for the tips, and I will start to deal with this concernments. :D

**Comment by colinbull** [comment] 2017-05-18 21:28
Just a thought on the taking dependencies, we could try and internalise the dependancy using ilrepack as part of the build. However I have no idea how this behaves with type providers it would however be interesting to find out..

**Comment by Thorium** [comment] 2017-05-18 21:56
I think the whole universe is depending James Newton-King. We can load the dlls dynamically and call with reflection to pretend that we are still in our own universe, but all the other Nuget-packages load that to your server memory anyway.

**Comment by pezipink** [comment] 2017-05-19 06:48
Yes, I wasn't saying we should never introduce dependencies, if they are they needed and it fits then it fits ...

**Comment by Thorium** [comment] 2017-09-13 08:55
Just an idea, one way to do this could be:

1. Create a typeprovider method "Offline" taking a path as parameter.
2. For that create a SaveNow-property that would save it design-time like Ross' typeprovider games, giving the result as another method.
3. The save method would just serialize the concurrentdictionarys via some new interface call.
4. Then we maybe can have corresponding offline parameter, or maybe we would need another static parameter to load the file to memory when compiling.

```fsharp
ctx.Offline(@"c:\sqlprovider.cache").SaveNow.``Save failed: Not enough disk space``
```

That could be then extended with another save method that would save the context in a background thread every 3 minutes if the data connection is available.

**Comment by pezipink** [comment] 2017-09-13 16:27
Interesting idea, very much non-standard!   Would be cool to try as an experiment.

**Comment by object** [comment] 2018-04-07 11:35
After our conversation yesterday at F# Exchange I am reviewing the code to figure out how we can add this feature. Please check what I have in mind and correct me if some of my assumptions are not correct.

1. We can use DataSet capabilities to save and load data schema as @Thorium suggested so there's no need to bring additional dependencies.

2. An addition static SqlDataProvider parameter SchemaCache can be introduced to point to file(s) with data schema(s), more about it in p.5.

3. If SchemaCache is not set or points to a non-existing file, SqlDataProvider will behave as today, resolving the schema from the actual database. This will make it easy to configure cache once and enable it only when needed by placing the cache file into the specified location.

4. There will be a new SqlDataProvider method SaveSchema (may also have LoadSchema for symmetry but I am not sure about scenario when it may be used).

5. Now what to save? I think saving the whole schema (actually schemas) can be an overkill. I can only imagine how many megabytes it will take to save all schemas for the Oracle database in our organization, and ours is far from biggest ones. Here what can be done:

- define a record type SchemaCache:
{ SchemaName: string
  FilePath: string }
- specify schema cache setting when saving it, e.g. SaveSchema({ SchemaName = "main"; FilePath = @"C:\Temp\main.xml"})
- since we already support tableNames for some databases, save only schema for the specified tables if it's specified, e.g. if tableNames are set to "products,customers" then SaveSchema will only save schema for those two tables.
- I am only familiar with Oracle and MS SQL Server, so I don't know if there is any database that don't have a concept of schema/catalog/database name. If there is such, then SchemaName can be an empty string (or made an option). Then we need to define semantics of missing schemaName for databases that support that. I still think there is no use for caching everything in such case. Caching schema is a kind of a hack to solve lost connectivity problem, so developers must be explicit in specifying what exactly they need to cache to reduce chances of accidentally cached schemas that will later go out of sync.

6. It will be up to a developer to call SaveSchema. This call should probably be not a part of a code running in a production. Something that can be executed from a script perhaps.

7. Now when the schema(s) is saved, it will be retrieved whenever SchemaCache is set, so there will be no need to load it in client code explicitly using LoadSchema.

Example: SchemaCache = [{SchemaName = "main"; FilePath = @"C:\Temp\main.xml"}]
For databases without support for multiple schemas (if any): [{SchemaName = ""; FilePath= @"C:\Temp\schema.xml"}] 

NB! Having written these notes, I've found Owner parameter that can, depending on the database vendor, specify schema or database name. If this is sufficient to resolve schema name, we may not even need a record type SchemaCache and can simply specify the file path of the schema for the respective owner. This will make better reuse of existing configuration settings but leaves a question of how to save/load multiple schemas. IMHO it may be OK to restrict caching to a single schema, so SchemaCache will require Owner to be set for multi-schema databases, and if a project uses schemas from multiple owners it will need to define multiple context types. Something to discuss, but if we make such restriction, then SchemaCache parameter can be renamed to SchemaPath (string) and SaveSchema will have a single string parameter specifying the file path. The rest will be figured out from Owner and TableNames values.

**Comment by object** [comment] 2018-04-08 09:29
Saving concurrent dictionaries will be more efficient than using legacy DataSet (and who loves XML?). The only argument in favor of DataSet schema is that it's already there and doesn't need bringing new dependencies. And it should be ok to deal with provider-specific dictionaries. But what will be a serialization format? JSON? Bring JSON.NET dependency just because of this feature?

**Comment by object** [comment] 2018-04-08 09:35
And if we split the implementation into two parts:
1. Extending SqlDataProvider with new methods and instantiation parameters
2. Schema serialization format

then if we agree about 1, I can start working on it using whatever serialization, and we can finalize schema format later. So if you have any input on the part 1 (e.g. support for saving multiple schemas per context, naming of new parameters and methods etc.), please let me know.

**Comment by object** [comment] 2018-04-08 09:48
More on serializers with .NET Core support: https://github.com/dotnet/corefx/issues/6564

> Please consider other serializers in .NET Core such as DataContractSerializer (DCS), DataContractJsonSerializer (DCJS) and XmlSerializer, which are and will continue to be supported in .NET Core. Of course, you can also consider 3rd party serializers built on .NET Core.

**Comment by Thorium** [comment] 2018-04-09 07:05
I think compile-time offline caching is not performace-critical, so probably any serialization will do.
We can split the implementation into two parts.

Regardless of the serialization format, there are still two options:

- Save the cache only, by the development time, the content that is required to build the system. 
- Or fetch and save the whole database schema.

Initially I would say that the first one sounds better, as some people are using huge Oracle schemas.
I would prefer that we start with as simple solution as possible and solve more complex scenarios when needed.

**Comment by object** [comment] 2018-04-09 10:12
I also think the 1st sounds better to begin with. I will do some experiments in a new branch and let you review results once I get something worthy.

**Comment by object** [comment] 2018-04-11 10:09
@Thorium I forked the code, experimenting with it right now and I need some tips regarding how I can only save the part of the schema referenced by the current context, not the whole db schema. Here's what I did so far:

1. Defined SaveContextSchema method in SqlDesignTime.fs:
`yield ProvidedMethod("SaveContextSchema",[ProvidedParameter("filePath", typeof<string>)],typeof<unit>, invokeCode = fun args -> <@@ ((%%args.[0] : obj) :?> ISqlDataContext).SaveContextSchema((%%args.[1] : string)) @@>) :> MemberInfo
`

2. Extended ISqlDataContext with a new method SaveContextSchema:
`abstract SaveContextSchema          : string -> unit
`

3. Added prototype of the implementation of SaveContextSchema in SqlRuntime.DataContext. The implementation is currently serializing tables using DataContractJsonSerializer, just to try that this works:

```
        member __.SaveContextSchema(filePath) =
            use con = provider.CreateConnection(connectionString)
            providerCache
            |> Seq.iter (fun prov -> 
                let prov = prov.Value
                let tables = prov.GetTables(con,caseSensitivity)
                tables
                |> List.iter (fun table->
                    use ms = new System.IO.MemoryStream()
                    let ser = new System.Runtime.Serialization.Json.DataContractJsonSerializer(table.GetType())
                    ser.WriteObject(ms, table);  
                    let json = ms.ToArray();  
                    System.IO.File.AppendAllText(filePath, System.Text.Encoding.UTF8.GetString(json, 0, json.Length))

```

When I test the implementation I see that SaveContextSchema saves everything, all database tables. This is of course a problem because just a JSON with all Oracle tables (no columns) take about 0.5 MB in our case. It can easily become 100 times larger with all column information. But I can't figure out how I can obtain the schema for only referenced tables/columns. Any tips?

**Comment by object** [comment] 2018-04-11 10:44
@pezipink So what is your take on this use case? Do you think it's acceptable to just cache everything (this looks to be a straightforward task) since we are talking about quite special case - if anyone want to have a schema offline they might as well afford generation of multimegabyte file? Or we should strive to find a way of caching schema just for the tables used but then I need some hints from you guys, can't figure out myself how I will obtain such schema.

**Comment by Thorium** [comment] 2018-04-11 11:30
Also I think you shouldn't run it on `invokeCode` as that is never invoked on design time, right?
Rather add the code to `AddMembersDelayed` or `AddXmlDocDelayed` and return the save-result as a new property (if you use membersdelayed) or a string (if you use xmldocdelayed).

**Comment by object** [comment] 2018-04-11 11:30
@Thorium But how do I get access to them from the common provider code since all lookup dictionaries are defined inside its respective provider? Should each provider expose lookup dictionaries?

**Comment by Thorium** [comment] 2018-04-11 11:32
I would vote for a common tooling method(s) that saves the data, and call it inside each provider implementation. There is probably not enough common API that they could be exposed nicely.

**Comment by pezipink** [comment] 2018-04-11 12:58
I think it is acceptable if that is what the user really wants, but it does go against the spirit of what I as initially trying to achieve, and bringing it closer to what SQLMetal does.

I agree, add it to the interface and have the providers serialize their dictionaries.  You will need to be careful though because things like `AddMemebersDelayed`  get called a bunch of times on different threads and other crazy things, likely you will need some locking, and maybe to be clever about how you serialize so it isn't trying to re-serialize the whole thing all the time.  I foresee some unforeseen adventures for you  !

Also, it is great you are having a go at this piece of work.  Thanks ! :)

**Comment by object** [comment] 2018-04-11 13:05
Alright, so I will look into caching provider-specific concurrent dictionaries and will use AddMembersDelayed. I will probably ask more questions on the way.

**Comment by object** [comment] 2018-04-13 05:46
Question regarding differences in lookup dictionaries for different providers.

Majority of the providers use the following set of dictionaries:
    let pkLookup = ConcurrentDictionary<string,string list>()
    let tableLookup = ConcurrentDictionary<string,Table>()
    let columnLookup = ConcurrentDictionary<string,ColumnLookup>()
    let relationshipLookup = ConcurrentDictionary<string,Relationship list * Relationship list>()

However there are some exceptions:
1. Postgresql and SQLite use Dictionary (not ConcurrentDictionary) for relationship cache. Can we change it to ConcurrentDictionary?
2. Oracle has its own set:
    let mutable primaryKeyColumn : IDictionary<string,PrimaryKey> = null
    let columnCache = new ConcurrentDictionary<string,ColumnLookup>()
    let mutable tableCache : Table list = []
    let relationshipCache = new ConcurrentDictionary<string, Relationship list * Relationship list>()
Can we unify it with the rest?
3. ODBC doesn't have relationship dictionary (I suppose it doesn't support relations)

If these differences are not intentional, I can make all providers use the same set but then since we plan to expose new common functionality based on schema cache, should these collections be moved to a common type that combine them all? Then they can all share common schema cache implementation.
/cc @Thorium @pezipink

**Comment by Thorium** [comment] 2018-04-13 07:37
1. Dictionary was used before ConcurrentDictionary. VS threading is mysterious, so concurrent may be safer. Can be changed.
2. I know nothing about Oracle provider. However best practices in .NET has usually been that the container (dictionary itself) is immutable: "If replacing the collection is a goal, the preferred design pattern is to include a method to remove all the elements from the collection and a method to re-populate the collection. " - Microsoft
3. Yes I think ODBC doesn't have a generic schema that would desctibe the relationships, so the user has to write the joins manually. I usually prefer the manual way anyways.

One thing to consider is that you may have multiple database connections, e.g. both MySQL and Postgres inside one program, or two same type connections to different databases. So now that the containers are not global but inside a provider, the caches wont mess each other. As long as that works, the cache implementation can be common.

**Comment by object** [comment] 2018-04-13 07:46
Of course container instances should be per provider/connection. I meant we could have a common type that will wrap schema caches but each provider/connection will continue create and manage instances of such common type.

**Comment by Thorium** [comment] 2018-04-13 08:30
Yes, that would be good. :-)

**Comment by object** [comment] 2018-04-19 12:10
I have implemented caching of schema which I am currently testing in my branch (https://github.com/object/SQLProvider/tree/schema_cache), works with Oracle, will run some tests with MS SQL Server later.

This appeared to be quite a big change. 

1. I began with generalization of lookup collections (tables, columns, primary keys, relationships), so now all providers store these schema elements using common type.
2. Next was to serialize and deserialize a new type SchemaCache. This was implemented using DataContractJsonSerializer, so we don't need to drag new dependencies.
3. A new method SaveContextSchema has been added to an SQL provider. I named it SaveContextSchema, not just SaveSchema or SaveSchemaCache to emphasize that it's not a full schema but a part of it used in the current scope.
4. A new instantiation parameter ContextSchemaPath has been introduced. Contains a refererence to previously stored context schema.
5. The last and biggest change was to go through the whole code base and ensure every place that uses connection to an actual database has a fallback for offline mode. There were many places, most of them inside the huge function createTypes (part of SqlDesignTime.fs).
6. The set (tables, columns, primary keys, relationships) doesn't cover all schema elements. For example, stored procedures are not covered, GetTableDefinitions and GetColumnDefinitions require live connection. If client code depends on them, it won't support offline mode. But I believe majority scenarios don't need it.

With all these changes I can now write the following code:

```
type sql = SqlDataProvider< 
              ConnectionString = "my connection string",
              DatabaseVendor = Common.DatabaseProviderTypes.ORACLE,
              ResolutionPath = ResolutionPath,
              IndividualsAmount = 1000,
              UseOptionTypes = true >
let dbContext = sql.GetDataContext()

let profiles = 
    query { for p in dbContext.MyDatabase.Profiles do
            where (p.Media = "video") 
            select p.Description }
profiles |> Seq.toList

dbContext.SaveContextSchema(@"C:\TEMP\Schema.txt")

```
Then I can disconnect machine from the internet and replace the code with the following:

```
type sql = SqlDataProvider< 
              ConnectionString = "my connection string",
              DatabaseVendor = Common.DatabaseProviderTypes.ORACLE,
              ResolutionPath = ResolutionPath,
              IndividualsAmount = 1000,
              UseOptionTypes = true,
              ContextSchemaPath = @"C:\TEMP\Schema.txt" >
let dbContext = sql.GetDataContext()

let profiles = 
    query { for p in dbContext.Granitt.Profiles do
            where (p.Media = "video") 
            select p.Description }
profiles |> Seq.toList

```
And the code will compile.

Let me know what do you think about this approach. It would be great to test it on other databases than Oracle and MS SQL Server.

**Comment by Thorium** [comment] 2018-04-19 14:04
1. What happens on runtime, if my Azure SQL-connection fails for 10sec? I will get error and not incorrect query results, right?
2. People who build the provider off-line are probably using CI. So if I do the build it in the continious delivery machine, I probably want to do the release package also from that machine. It shouldn't matter, right? So that the real executable build off-line is as functional as the one build with database-connection online?

**Comment by object** [comment] 2018-04-19 14:49
It's up to us to define behavior, but this is how it is currently implemented.

1. If ContextSchemaPath is not set, provider works as today, it requires connection to the database at design and compile time.
2. If ContextSchemaPath is set but points to a non-existing file, provider also works as today and requires  connection to the database.
3. If ContextSchemaPath is set and points to an existing file, provider doesn't use ConnectionString to resolve schema and instead uses schema cache serialized from the specified file.

Reasoning behind this behavior: it would be nice to avoid unnecessary edits of the SqlProvider constructor properties just to enable and disable offline mode. SqlProvider construction parameters can be set once, and offline mode can be turned on based on the presence of the specified file. So it will be completely up to the development team when and where the place scheme cache file to control offline mode.

**Comment by Thorium** [comment] 2018-04-19 15:33
Procedures are quite commonly used, GetSprocs returns `Sproc list` so that maybe could be added to support the sprocs, if the params do serialize correctly (`IDbConnection -> QueryParameter list` functions). Individuals...no-one probably uses them anyways other than exploring the data at design-time.

**Comment by Thorium** [comment] 2018-04-19 16:53
I thought that this would save the file on design time. Instead it saves the cache at runtime.
Ok, that's fine, just needs one more step for the user to run the code... Is there all the information at cache on runtime?

**Comment by object** [comment] 2018-04-19 17:34
I just tested with SQL Server on Linux and SQL Provider built on Mac. Worked fine.

"I thought that this would save the file on design time. Instead it saves the cache at runtime."

I guess I didn't fully grasp this scenario. Especially since I was testing it from an F# script where there is not much practical difference between design-time and runtime. I can certainly change it but can please clarify step by step how schema cache for the current context will be save at design-time?

**Comment by object** [comment] 2018-04-19 17:57
I've re-read one of your comments. Here is what you meant, right?

dbContext.ContextSchema(@"C:\TEMP\Schema.txt").SaveNow.``Error``

But can it be shorter?

dbContext.ContextSchema(@"C:\TEMP\Schema.txt").Save.Now

**Comment by Thorium** [comment] 2018-04-19 17:58
Tested with MySQL, it works, but the problem is that `ctx.SaveContextSchema("c:\\test2.txt")` has to be called as the last line in your program. Which is not easy if you are not going to execute the whole program (e.g. I have a web server, and each method is called only when action is done, so I should surf the whole UI through before saving).

If we could do it design time, the design time might have loaded already everything for the compilation?
(I'm not sure but could be?)
Something like this (psedo, not working code) to SqlDesignTime.fs (expecting that ContextSchemaPath would be always defined and we would check the IsOffline some other way):

```fsharp
let saveResponse = ProvidedTypeDefinition("SaveContextResponse",None, isErased=true)
saveResponse.AddMemberDelayed(fun () -> 
    lock mySaveLock (fun() ->
        let result = 
            if String.IsNullOrEmpty contextSchemaPath then
                try
                    if not (System.IO.File.Exists contextSchemaPath) then
                        System.IO.File.Create(contextSchemaPath).Dispose()
                    prov.GetSchemaCache().Save contextSchemaPath
                    "Saved " + contextSchemaPath + " at " + DateTime.Now.ToString("hh:mm:ss")
                with
                | e -> "Save failed: " + e.Message
            else "ContextSchemaPath is not defined"
        ProvidedMethod(result,[],typeof<unit>, invokeCode = empty) :> MemberInfo
    )
)
let m = ProvidedMethod("SaveContextSchema",[], (saveResponse :> Type), invokeCode = fun args -> <@@ "" @@>)
m.AddXmlDocComputed(fun () -> 
    if String.IsNullOrEmpty contextSchemaPath then "ContextSchemaPath static parameter has to be defined to use this function."
    else "Schema location: " + contextSchemaPath + ". Write dot after this method to see the save result."
    )
yield m :> MemberInfo
```

**Comment by object** [comment] 2018-04-19 18:35
"If we could do it design time, the design time might have loaded already everything for the compilation?"

Will it? My tests showed that the cache contained all tables but columns for only tables referenced in the current scope. So if I have other source files referencing other tables their schema would not be saved. This is partly why I went this path - I have to put some code referencing all tables that I want to be cached in order to save the schema. So most likely I will need to write a small design-time script for schema cache saving.

An alternative to this would be to force saving the complete schema for the whole database. But in the comments above we sort of agreed that we don't want that.

Another (new) option might be defining a method for explicit referencing certain schema elements and saving them in the cache, e.g.:

ctx.ContextSchema(@"C:\Temp\Schema.txt", [ctx.Main.Customers; ctx.Main.Product; ctx.Main.Orders]).SaveNow

**Comment by Thorium** [comment] 2018-04-19 20:11
I don’t know how easy it’s to get other than the static parameters design-time, without referencing FSharp.Compiler.

--
- Tuomas
Sent from my Windows 10 phone

**Comment by Thorium** [comment] 2018-04-19 21:15
”My tests showed that the cache contained all tables but columns for only tables referenced in the current scope”

What is the scope here? Does that mean that if you have 100 different queries, there are actually 100 different concurrent column caches? I think that is not what we want.

--
- Tuomas

Sent from my Windows 10 phone

**Comment by object** [comment] 2018-04-20 07:52
No, there is only one schema cache per provider. So each query just adds to the context.

But we probably see two main usage scenarios: save a schema only for queries referenced in the context and save a schema for an application that uses many different queries in its different components, so it's hard to extract them all in one place, and then it's better to save the whole database schema.

What about ContextSchema and FullSchema with SaveNow design time method? And rename static parameter to SchemaCachePath.

Perhaps we should not give a developer a choice of selecting a filename, just schema folder path, so provider can store there files using internal names that will contain timestamp, as you suggested in your example.

I will be away until Tuesday, but will be checking the thread.

**Comment by Thorium** [comment] 2018-04-20 10:56
Created PR for you to do the saving at design-time. Try it, and let me know what you think. Works well for me, saves the whole used schema. So that you can use it to build the project.

What comes to stored procedures, I tried quickly this: Added a storage for sprocs:

```fsharp
and internal SchemaCache =
    { ...
      Procedures    : ResizeArray<Sproc>
      IsOffline     : bool }
    with
        static member Empty = { 
            ...
            Procedures = ResizeArray<Sproc>()
            IsOffline = false }
```

Then just modified procedure calls from e.g. `member __.GetSprocs(con) = MSSqlServer.connect con MSSqlServer.getSprocs` to:

```fsharp
        member __.GetSprocs(con) = MSSqlServer.connect con MSSqlServer.getSprocs
            if schemaCache.IsOffline then schemaCache.Procedures |> Seq.toList
            else
                let r = MSSqlServer.connect con MSSqlServer.getSprocs
                schemaCache.Procedures.AddRange r
                r
```

...but as expected, the DataContractJsonSerializer fails to serialize the type Sproc. It's a recursive f# type with functions.

**Comment by object** [comment] 2018-04-27 12:55
I have merged a PR in my repo and left a comment about its behavior, but I believe before advancing we need to have a closer look at how to save the schema covering all queries in the app source code.
While I was away, I met @sergey-tihon and told him about this idea. He found it too limiting if the schema is saved only for the queries listed in the current file or script, and he suggested to explore possibilities of saving schema in the end of the compilation. E.g.:

1. SaveContextSchema can still be defined and used as it's done now, for scenarios where it's easy to reference all referenced schema elements in a single source file.
2. During the solution compilation a type provider is instantiated, and it must build the sufficient schema for all queries referenced in the code.
3. The schema can be saved in the end of the compilation.

Now I must say that I lack the knowledge of how F# type providers are instantiated during the compilation phase and whether it's possible them to react on build events. But if this is possible, it opens for generation of schema based on all referenced entities.

/cc @Thorium

**Comment by Thorium** [comment] 2018-04-27 15:01
> He found it too limiting if the schema is saved only for the queries listed in the current file or script

What you mean by that? 
Doesn't it  save the whole solution loaded to the editor?
And you don't share SQLProvider context over different solutions anyway, there can be different file per solution.

**Comment by object** [comment] 2018-04-30 13:11
Sorry for delay with response. I wanted to run more tests. In short: no, it doesn't save the schema for the whole solution. Here's how I tested.

1. I added 2 source files to the solution, both referring to the same SQL context type. Let's call them ModuleA and ModuleB.
2. ModuleA contained a function that ran a query from an Oracle SchemaA. Here's the query

        query { for p in ctx.SchemaA.MyTable do
                where (p.Media = "video") 
                select p.Description }

3. ModuleB contained a function that ran a query from an Oracle SchemaB. 

        query { for p in ctx.SchemaB.MyTable do
                where (p.Media = "video") 
                select p.Description }

Both SchemaA and SchemaB (or "owner", I believe it's the same in Oracle) use the same connection string.
The program compiled fine, at that time I didn't define ContextSchemaPath.

4. Then I defiend ContextSchemaPath and at the bottom of the ModuleA wrote the following:

sql.GetDataContext().SaveContextSchema().

The schema was saved according to the ContextSchemaPath.

5. But then if I try to compiled the solution, the compilation fails at ModuleB with the following errors:

error FS0039: The field, constructor or member 'Media' is not defined.
error FS0039: The field, constructor or member 'Description' is not defined.

When I inspect the schema file, I can see that it saved definitions for all tables for all schemas, but only columns referenced in ModuleA where I put a call to SaveContextSchema.

6. If I duplicate the query from ModuleB in ModuleA and then save context schema, then the generated file is larger and compilation succeeds.

So there is a problem of schema cache applied only to the scope of the current file. Event though the whole solution compiles fine, the saved cache is restricted to columns referenced in the current file.
Another observation: even though compilation fails, Intellisense works! If I hover a cursor over columns in file ModuleB, I see a tooltip with column names and types. Somehow there are two schema contexts generated, and the one that is saved is not generated for the whole solution.

**Comment by Thorium** [comment] 2018-04-30 14:15
So they shared the same ctx?

> Another observation: even though compilation fails, Intellisense works!

I was kind of hoping to save the intellisense-schema. Does this mean the cache dictionaries should be static totally and not per provided ctx? (Which could introduce new problems like cache not invalidating ever.)

**Comment by sergey-tihon** [comment] 2018-04-30 16:00
what if you will go another way...
- Save provided typed (for offline use) only during compile time. (Using `IsHostedExecution` or `IsInvalidationSupported` from [TypeProviderConfig](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/compilerservices.typeproviderconfig-class-%5Bfsharp%5D) to distinguish the case then compiler execute TP).
- If you cannot connect to the database you do not fail immediately but try to lookup types from a local file created during previous compilation.

**Comment by object** [comment] 2018-05-01 09:41
@sergey-tihon This sounds interesting, but is there any way for an instantiated provider to detect that all provided type are created, so it's a right time to save the schema? Are there any callbacks that hits a provider about compilation stages?

**Comment by sergey-tihon** [comment] 2018-05-02 08:47
> is there any way for an instantiated provider to detect that all provided type is created, so it's a right time to save the schema?

I see... this is complicated because you do a lot of work lazily ... I do not know such callbacks that can help here.

The only solution that I see - updates the cache every time when compiler call TP

Instead of this 
```fsharp
ty.AddMembersDelayed(builderFunc)
```
use 
```fsharp
ty.AddMembersDelayed(builderFunc >> cacheFunc)
```

with some smart cache invalidation inside `cacheFunc`. But this path does not look easy ...

**Comment by object** [comment] 2018-05-02 09:14
Thanks for the tip. Will give it a try.

**Comment by Thorium** [comment] 2018-05-03 15:30
Merged. NuGet package 1.1.42.

**Closed by Thorium** 2018-05-03 15:30 UTC
Labels: enhancement

**Comment by object** [comment] 2018-05-08 12:40
Agree, we have to be careful about supporting such implicit actions. The essence of F# type providers is that they generate types on the fly based on the actual data. Once there are multiple ways to bypass the live connections, things can become hard to control. I believe we should let the feature be used by different developers in different teams and then decide about improvements.

What kind of runtime error are you encountering? During the compilation or when the schema file is being generated?

**Comment by piaste** [comment] 2018-05-23 11:11
> What kind of runtime error are you encountering? During the compilation or when the schema file is being generated?

Neither, both compilation and schema generation work fine. The error, strangely enough, is at *runtime*, it happens when the application calls `.GetDataContext(runtimeConnString)`. It throws this exception:

> The data contract type 'Microsoft.FSharp.Collections.FSharpMap`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[FSharp.Data.Sql.Schema.Column, FSharp.Data.SqlProvider, Version=1.1.42.0, Culture=neutral, PublicKeyToken=null]]' cannot be deserialized because the required data members 'comparer, tree' were not found.

The line is [here](https://github.com/fsprojects/SQLProvider/pull/545/files#diff-8d7a61e9b41f3e400217abeddcfb6083R603), it seems the `DataContractSerializer` for the .NET Core 2.0 runtime doesn't like the `ColumnLookup` type (`Map<string, Column>`), while the compilation runs on the full framework and doesn't throw.

After some fiddling, turns out the reason I was seeing it only at runtime is that when I run the application on my machine, `SchemaCache.LoadOrEmpty` finds the file and attempts to load it anyway. (If I manually rename the .json file before launching the application, the error doesn't occur.)

This definitely needs fixing, as the library shouldn't try to load a random file path at runtime. It should be enough to always pass an empty `contextSchemaPath` to `createProvider` in `SqlRuntime.DataContext.fs`, I think?

**Comment by keyset** [comment] 2018-06-07 16:20
I'm running into this same problem. The type provider is locating the schema file and attempting to use it as a data source at runtime. I've filed issue #552 for this.

**Comment by ngriggsnd** [comment] 2018-08-12 19:12
Hello, 

Thank you all for your work on the SQLProvider.

I have been trying to use it recently to access an Oracle database.

All has gone well expect for saving the SaveContextSchema(). feature as I receive the following error message: "Save failed: Access to path 'C:\Users\nathaniel\Desktop' is denied."

Any guidance would be greatly appreciated.

{Code included for reference, note that it works perfectly well as a .fsx file returning result of queries on the database perfectly fine but the SaveContextSchema has given troubel.}

#r @"C:\Users\nathaniel\documents\visual studio 2015\Projects\Connect To Oracle\packages\SQLProvider.1.1.48\lib\net451\FSharp.Data.SqlProvider.dll"

open FSharp.Data.Sql

let [<Literal>] Connection_String = @"User Id=hr;Password=password;Data Source=localhost"
let [<Literal>] Resolution_Path = @"C:\Users\nathaniel\documents\visual studio 2015\Projects\Connect To Oracle\packages\Oracle.ManagedDataAccess.12.2.1100\lib\net40"
let [<Literal>] Oracle_Owner = @"hr"

// C:\Users\nathaniel\Documents\Visual Studio 2015\Projects\Connect To Oracle\packages\Oracle.ManagedDataAccess.12.2.1100\readme.txt

type Oracle_SQL = SqlDataProvider<
                                  ConnectionString = Connection_String,
                                  DatabaseVendor = Common.DatabaseProviderTypes.ORACLE,
                                  ResolutionPath = Resolution_Path,
                                  Owner = Oracle_Owner,
                                  ContextSchemaPath = @"C:\Users\nathaniel\Desktop" ,
                                  UseOptionTypes = true>

let database = Oracle_SQL.GetDataContext(SelectOperations.DatabaseSide)
 // limit data passed back and forth by chosing SelectOperation.DatabaseSide instead of DotNetSide

let result_of_query = 
    query {
            for x in database.Hr.Employees do
            select (
                        x.Email
                    )
          }
    |> Seq.toArray

Oracle_SQL.GetDataContext(SelectOperations.DatabaseSide).SaveContextSchema().
`

**Comment by object** [comment] 2018-08-12 19:25
@ngriggsnd "Save failed: Access to the path 'C:\Users\nathaniel\Desktop' is denied" doesn't necessarily mean that your app doesn't have rights to save the schema. It can also mean that the file is locked by another app (or even the same app). I don't know what it can be, so you need to investigate it yourself.

**Comment by ngriggsnd** [comment] 2018-08-12 22:56
@object 

Good news: I was able to save a schema file by changing "ContextSchemaPath = @"C:\Users\nathaniel\Desktop" to ContextSchemaPath = @"C:\Users\nathaniel\Desktop\meta.schema"

However, when I go to use the ContextSchemaPath static parameter in the .fs file, I am still receiving a compile time error/warning when trying to "dot" into the database. I am using the exact same query as in the .fsx file used to create the meta.schema file. So, from what I can tell, the lazy nature of the loading should not be an issue. 

Please let me know if I am missing something or using the SQLProvider improperly. Thank you for your assistance.

**Comment by ngriggsnd** [comment] 2018-08-13 16:55
@object

I was able to solve all compile-time issues by adding reference to System.Data as suggested and reported on this thread https://github.com/fsprojects/SQLProvider/issues/490 .

Please let me know if and how I might contribute to the documentation so that others may benefit.

**Comment by object** [comment] 2018-08-13 18:06
@ngriggsnd That's good! Thanks for letting me know.
I am not sure how the documentation should be updated for others to avoid this issue. My contribution to the project has been mainly around schema caching and Oracle provider, @Thorium should have better idea about whether System.Data reference should be mentioned. But you can browse current docs and if you have some suggestion about how to extend them, please go ahead and send a PR.

**Comment by dohly** [comment] 2018-08-24 20:39
Hello @object !
SaveContextSchema() doesn't work for me. I'm using SQL server express.
Everything works well if ContextSchemaPath is not specified. 
Otherwise it doesn't work.
Please help. Thanks.
![1](https://user-images.githubusercontent.com/1271285/44606675-550db800-a807-11e8-97c9-683adbbce3fc.gif)

**Comment by Thorium** [comment] 2018-08-25 08:42
@dohly: The schema-files are not compatible between 1.1.48 and 1.1.49. So if you generated schema file with 1.1.48, you have to re-genarete it for 1.1.49. The reason is that 1.1.49 added serialization of stored procedures.

**Comment by object** [comment] 2018-08-25 09:34
Oh that's good to know. Was about to upgrade SQLProvider myself :-)
